/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditCardsRouteImport } from './routes/credit-cards'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPersonalRouteImport } from './routes/dashboard.personal'
import { Route as DashboardLoansRouteImport } from './routes/dashboard.loans'
import { Route as DashboardGrantsRouteImport } from './routes/dashboard.grants'
import { Route as DashboardCardsRouteImport } from './routes/dashboard.cards'
import { Route as DashboardBusinessRouteImport } from './routes/dashboard.business'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCardsRoute = CreditCardsRouteImport.update({
  id: '/credit-cards',
  path: '/credit-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPersonalRoute = DashboardPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoansRoute = DashboardLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGrantsRoute = DashboardGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCardsRoute = DashboardCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessRoute = DashboardBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/credit-cards': typeof CreditCardsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/grants': typeof GrantsRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/personal': typeof PersonalRoute
  '/register': typeof RegisterRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/grants': typeof DashboardGrantsRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/personal': typeof DashboardPersonalRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/credit-cards': typeof CreditCardsRoute
  '/grants': typeof GrantsRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/personal': typeof PersonalRoute
  '/register': typeof RegisterRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/grants': typeof DashboardGrantsRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/personal': typeof DashboardPersonalRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/credit-cards': typeof CreditCardsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/grants': typeof GrantsRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/personal': typeof PersonalRoute
  '/register': typeof RegisterRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/grants': typeof DashboardGrantsRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/personal': typeof DashboardPersonalRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business'
    | '/contact'
    | '/credit-cards'
    | '/dashboard'
    | '/grants'
    | '/loans'
    | '/login'
    | '/personal'
    | '/register'
    | '/dashboard/business'
    | '/dashboard/cards'
    | '/dashboard/grants'
    | '/dashboard/loans'
    | '/dashboard/personal'
    | '/dashboard/profile'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business'
    | '/contact'
    | '/credit-cards'
    | '/grants'
    | '/loans'
    | '/login'
    | '/personal'
    | '/register'
    | '/dashboard/business'
    | '/dashboard/cards'
    | '/dashboard/grants'
    | '/dashboard/loans'
    | '/dashboard/personal'
    | '/dashboard/profile'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business'
    | '/contact'
    | '/credit-cards'
    | '/dashboard'
    | '/grants'
    | '/loans'
    | '/login'
    | '/personal'
    | '/register'
    | '/dashboard/business'
    | '/dashboard/cards'
    | '/dashboard/grants'
    | '/dashboard/loans'
    | '/dashboard/personal'
    | '/dashboard/profile'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessRoute: typeof BusinessRoute
  ContactRoute: typeof ContactRoute
  CreditCardsRoute: typeof CreditCardsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  GrantsRoute: typeof GrantsRoute
  LoansRoute: typeof LoansRoute
  LoginRoute: typeof LoginRoute
  PersonalRoute: typeof PersonalRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-cards': {
      id: '/credit-cards'
      path: '/credit-cards'
      fullPath: '/credit-cards'
      preLoaderRoute: typeof CreditCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/personal': {
      id: '/dashboard/personal'
      path: '/personal'
      fullPath: '/dashboard/personal'
      preLoaderRoute: typeof DashboardPersonalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/loans': {
      id: '/dashboard/loans'
      path: '/loans'
      fullPath: '/dashboard/loans'
      preLoaderRoute: typeof DashboardLoansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/grants': {
      id: '/dashboard/grants'
      path: '/grants'
      fullPath: '/dashboard/grants'
      preLoaderRoute: typeof DashboardGrantsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cards': {
      id: '/dashboard/cards'
      path: '/cards'
      fullPath: '/dashboard/cards'
      preLoaderRoute: typeof DashboardCardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business': {
      id: '/dashboard/business'
      path: '/business'
      fullPath: '/dashboard/business'
      preLoaderRoute: typeof DashboardBusinessRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBusinessRoute: typeof DashboardBusinessRoute
  DashboardCardsRoute: typeof DashboardCardsRoute
  DashboardGrantsRoute: typeof DashboardGrantsRoute
  DashboardLoansRoute: typeof DashboardLoansRoute
  DashboardPersonalRoute: typeof DashboardPersonalRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBusinessRoute: DashboardBusinessRoute,
  DashboardCardsRoute: DashboardCardsRoute,
  DashboardGrantsRoute: DashboardGrantsRoute,
  DashboardLoansRoute: DashboardLoansRoute,
  DashboardPersonalRoute: DashboardPersonalRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessRoute: BusinessRoute,
  ContactRoute: ContactRoute,
  CreditCardsRoute: CreditCardsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  GrantsRoute: GrantsRoute,
  LoansRoute: LoansRoute,
  LoginRoute: LoginRoute,
  PersonalRoute: PersonalRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
