/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditCardsRouteImport } from './routes/credit-cards'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPersonalRouteImport } from './routes/dashboard.personal'
import { Route as DashboardLoansRouteImport } from './routes/dashboard.loans'
import { Route as DashboardInternationalRouteImport } from './routes/dashboard.international'
import { Route as DashboardGrantsRouteImport } from './routes/dashboard.grants'
import { Route as DashboardCardsRouteImport } from './routes/dashboard.cards'
import { Route as DashboardBusinessRouteImport } from './routes/dashboard.business'
import { Route as ApiEmailReceiptRouteImport } from './routes/api.email-receipt'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminLoansRouteImport } from './routes/admin.loans'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminGrantsRouteImport } from './routes/admin.grants'
import { Route as AdminFundsRouteImport } from './routes/admin.funds'
import { Route as AdminCardsRouteImport } from './routes/admin.cards'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCardsRoute = CreditCardsRouteImport.update({
  id: '/credit-cards',
  path: '/credit-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPersonalRoute = DashboardPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoansRoute = DashboardLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInternationalRoute = DashboardInternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGrantsRoute = DashboardGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCardsRoute = DashboardCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessRoute = DashboardBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiEmailReceiptRoute = ApiEmailReceiptRouteImport.update({
  id: '/api/email-receipt',
  path: '/api/email-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoansRoute = AdminLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrantsRoute = AdminGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFundsRoute = AdminFundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardsRoute = AdminCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/credit-cards': typeof CreditCardsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/grants': typeof GrantsRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/personal': typeof PersonalRoute
  '/register': typeof RegisterRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/funds': typeof AdminFundsRoute
  '/admin/grants': typeof AdminGrantsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/email-receipt': typeof ApiEmailReceiptRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/grants': typeof DashboardGrantsRoute
  '/dashboard/international': typeof DashboardInternationalRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/personal': typeof DashboardPersonalRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/credit-cards': typeof CreditCardsRoute
  '/grants': typeof GrantsRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/personal': typeof PersonalRoute
  '/register': typeof RegisterRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/funds': typeof AdminFundsRoute
  '/admin/grants': typeof AdminGrantsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/email-receipt': typeof ApiEmailReceiptRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/grants': typeof DashboardGrantsRoute
  '/dashboard/international': typeof DashboardInternationalRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/personal': typeof DashboardPersonalRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRoute
  '/contact': typeof ContactRoute
  '/credit-cards': typeof CreditCardsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/grants': typeof GrantsRoute
  '/loans': typeof LoansRoute
  '/login': typeof LoginRoute
  '/personal': typeof PersonalRoute
  '/register': typeof RegisterRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/funds': typeof AdminFundsRoute
  '/admin/grants': typeof AdminGrantsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/email-receipt': typeof ApiEmailReceiptRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/grants': typeof DashboardGrantsRoute
  '/dashboard/international': typeof DashboardInternationalRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/personal': typeof DashboardPersonalRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/business'
    | '/contact'
    | '/credit-cards'
    | '/dashboard'
    | '/grants'
    | '/loans'
    | '/login'
    | '/personal'
    | '/register'
    | '/admin/admins'
    | '/admin/cards'
    | '/admin/funds'
    | '/admin/grants'
    | '/admin/kyc'
    | '/admin/loans'
    | '/admin/users'
    | '/api/email-receipt'
    | '/dashboard/business'
    | '/dashboard/cards'
    | '/dashboard/grants'
    | '/dashboard/international'
    | '/dashboard/loans'
    | '/dashboard/personal'
    | '/dashboard/profile'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business'
    | '/contact'
    | '/credit-cards'
    | '/grants'
    | '/loans'
    | '/login'
    | '/personal'
    | '/register'
    | '/admin/admins'
    | '/admin/cards'
    | '/admin/funds'
    | '/admin/grants'
    | '/admin/kyc'
    | '/admin/loans'
    | '/admin/users'
    | '/api/email-receipt'
    | '/dashboard/business'
    | '/dashboard/cards'
    | '/dashboard/grants'
    | '/dashboard/international'
    | '/dashboard/loans'
    | '/dashboard/personal'
    | '/dashboard/profile'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/business'
    | '/contact'
    | '/credit-cards'
    | '/dashboard'
    | '/grants'
    | '/loans'
    | '/login'
    | '/personal'
    | '/register'
    | '/admin/admins'
    | '/admin/cards'
    | '/admin/funds'
    | '/admin/grants'
    | '/admin/kyc'
    | '/admin/loans'
    | '/admin/users'
    | '/api/email-receipt'
    | '/dashboard/business'
    | '/dashboard/cards'
    | '/dashboard/grants'
    | '/dashboard/international'
    | '/dashboard/loans'
    | '/dashboard/personal'
    | '/dashboard/profile'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BusinessRoute: typeof BusinessRoute
  ContactRoute: typeof ContactRoute
  CreditCardsRoute: typeof CreditCardsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  GrantsRoute: typeof GrantsRoute
  LoansRoute: typeof LoansRoute
  LoginRoute: typeof LoginRoute
  PersonalRoute: typeof PersonalRoute
  RegisterRoute: typeof RegisterRoute
  ApiEmailReceiptRoute: typeof ApiEmailReceiptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-cards': {
      id: '/credit-cards'
      path: '/credit-cards'
      fullPath: '/credit-cards'
      preLoaderRoute: typeof CreditCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/personal': {
      id: '/dashboard/personal'
      path: '/personal'
      fullPath: '/dashboard/personal'
      preLoaderRoute: typeof DashboardPersonalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/loans': {
      id: '/dashboard/loans'
      path: '/loans'
      fullPath: '/dashboard/loans'
      preLoaderRoute: typeof DashboardLoansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/international': {
      id: '/dashboard/international'
      path: '/international'
      fullPath: '/dashboard/international'
      preLoaderRoute: typeof DashboardInternationalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/grants': {
      id: '/dashboard/grants'
      path: '/grants'
      fullPath: '/dashboard/grants'
      preLoaderRoute: typeof DashboardGrantsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cards': {
      id: '/dashboard/cards'
      path: '/cards'
      fullPath: '/dashboard/cards'
      preLoaderRoute: typeof DashboardCardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business': {
      id: '/dashboard/business'
      path: '/business'
      fullPath: '/dashboard/business'
      preLoaderRoute: typeof DashboardBusinessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/email-receipt': {
      id: '/api/email-receipt'
      path: '/api/email-receipt'
      fullPath: '/api/email-receipt'
      preLoaderRoute: typeof ApiEmailReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loans': {
      id: '/admin/loans'
      path: '/loans'
      fullPath: '/admin/loans'
      preLoaderRoute: typeof AdminLoansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grants': {
      id: '/admin/grants'
      path: '/grants'
      fullPath: '/admin/grants'
      preLoaderRoute: typeof AdminGrantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/funds': {
      id: '/admin/funds'
      path: '/funds'
      fullPath: '/admin/funds'
      preLoaderRoute: typeof AdminFundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cards': {
      id: '/admin/cards'
      path: '/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AdminCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminCardsRoute: typeof AdminCardsRoute
  AdminFundsRoute: typeof AdminFundsRoute
  AdminGrantsRoute: typeof AdminGrantsRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminLoansRoute: typeof AdminLoansRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminCardsRoute: AdminCardsRoute,
  AdminFundsRoute: AdminFundsRoute,
  AdminGrantsRoute: AdminGrantsRoute,
  AdminKycRoute: AdminKycRoute,
  AdminLoansRoute: AdminLoansRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBusinessRoute: typeof DashboardBusinessRoute
  DashboardCardsRoute: typeof DashboardCardsRoute
  DashboardGrantsRoute: typeof DashboardGrantsRoute
  DashboardInternationalRoute: typeof DashboardInternationalRoute
  DashboardLoansRoute: typeof DashboardLoansRoute
  DashboardPersonalRoute: typeof DashboardPersonalRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBusinessRoute: DashboardBusinessRoute,
  DashboardCardsRoute: DashboardCardsRoute,
  DashboardGrantsRoute: DashboardGrantsRoute,
  DashboardInternationalRoute: DashboardInternationalRoute,
  DashboardLoansRoute: DashboardLoansRoute,
  DashboardPersonalRoute: DashboardPersonalRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BusinessRoute: BusinessRoute,
  ContactRoute: ContactRoute,
  CreditCardsRoute: CreditCardsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  GrantsRoute: GrantsRoute,
  LoansRoute: LoansRoute,
  LoginRoute: LoginRoute,
  PersonalRoute: PersonalRoute,
  RegisterRoute: RegisterRoute,
  ApiEmailReceiptRoute: ApiEmailReceiptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
